### ISSUE TITLE
Setup Netlify and deploy the project

### ISSUE THREAD

**Issue by AllanSaleh** [ReCoded-Org/-capstone-IQLBPS-jobie#7]
## Summary

Deploy the project to Netlify. Also, make sure that CD runs every time there is a PR in the repo.

### Screenshots
N/A
### Basic example
N/A

### Motivation

So that we are able to see a live version of the project and the changes are shown every time we make a PR

**Comment by AllanSaleh** [comment]
Awesome work, @marwazpov !🙌

**Comment by marwazpov** [comment]
Thank you so much @AllanSaleh for helping!🙌
